<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>230a8fe9-cad8-4751-8167-327a5404cab2</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" Version="13.6.0" />
    <PackageReference Include="CommunityToolkit.Aspire.OllamaSharp" Version="13.6.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.13.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.2-preview.1" />
    <PackageReference Include="Pgvector.Dapper" Version="0.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PgVectorVectorSearch.ServiceDefaults\PgVectorVectorSearch.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
