<Project Sdk="Aspire.AppHost.Sdk/13.6.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>9b2cf7a1-3fe9-433e-9eb3-1efb453baa25</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.6.0" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" Version="13.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PgVectorVectorSearch.API\PgVectorVectorSearch.API.csproj" />
  </ItemGroup>

</Project>
